/*
 *
 * Copyright 2016 CUBRID Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

/*
 * db_function.hpp
 */

#ifndef _DB_FUNCTION_HPP_
#define _DB_FUNCTION_HPP_

typedef enum
{
  /* aggregate functions */
  PT_MIN = 900, PT_MAX, PT_SUM, PT_AVG,
  PT_STDDEV, PT_VARIANCE,
  PT_STDDEV_POP, PT_VAR_POP,
  PT_STDDEV_SAMP, PT_VAR_SAMP,
  PT_COUNT, PT_COUNT_STAR,
  PT_GROUPBY_NUM,
  PT_AGG_BIT_AND, PT_AGG_BIT_OR, PT_AGG_BIT_XOR,
  PT_GROUP_CONCAT,
  PT_ROW_NUMBER,
  PT_RANK,
  PT_DENSE_RANK,
  PT_NTILE,
  PT_JSON_ARRAYAGG,
  PT_JSON_OBJECTAGG,
  PT_TOP_AGG_FUNC,
  /* only aggregate functions should be below PT_TOP_AGG_FUNC */

  /* analytic only functions */
  PT_LEAD, PT_LAG,

  /* foreign functions */
  PT_GENERIC,

  /* from here down are function code common to parser and xasl */
  /* "table" functions argument(s) are tables */
  F_TABLE_SET, F_TABLE_MULTISET, F_TABLE_SEQUENCE,
  F_TOP_TABLE_FUNC,
  F_MIDXKEY,

  /* "normal" functions, arguments are values */
  F_SET, F_MULTISET, F_SEQUENCE, F_VID, F_GENERIC, F_CLASS_OF,
  F_INSERT_SUBSTRING, F_ELT, F_JSON_OBJECT, F_JSON_ARRAY, F_JSON_MERGE, F_JSON_MERGE_PATCH, F_JSON_INSERT,
  F_JSON_REMOVE, F_JSON_ARRAY_APPEND, F_JSON_GET_ALL_PATHS, F_JSON_REPLACE, F_JSON_SET, F_JSON_KEYS,
  F_JSON_ARRAY_INSERT, F_JSON_SEARCH, F_JSON_CONTAINS_PATH, F_JSON_EXTRACT, F_JSON_CONTAINS, F_JSON_DEPTH,
  F_JSON_LENGTH, F_JSON_PRETTY, F_JSON_QUOTE, F_JSON_TYPE, F_JSON_UNQUOTE, F_JSON_VALID,

  F_REGEXP_COUNT, F_REGEXP_INSTR, F_REGEXP_LIKE, F_REGEXP_REPLACE, F_REGEXP_SUBSTR,
  F_ST_AFFINE, F_ST_AREA, F_ST_AREA_SPHEROID, F_ST_ASGEOJSON, F_ST_ASHEXWKB, F_ST_ASSVG, F_ST_ASTEXT,
  F_ST_ASWKB, F_ST_ASBINARY, F_ST_AZIMUTH, F_ST_BOUNDARY, F_ST_BUFFER, F_ST_BUILDAREA, F_ST_CENTROID,
  F_ST_COLLECT, F_ST_COLLECTIONEXTRACT, F_ST_CONCAVEHULL, F_ST_CONTAINS, F_ST_CONTAINSPROPERLY,
  F_ST_CONVEXHULL, F_ST_COVERAGEINVALIDEDGES, F_ST_COVERAGESIMPLIFY, F_ST_COVERAGEUNION, F_ST_COVEREDBY,
  F_ST_COVERS, F_ST_CROSSES, F_ST_DWITHIN, F_ST_DWITHIN_GEOS, F_ST_DWITHIN_SPHEROID, F_ST_DIFFERENCE,
  F_ST_DIMENSION, F_ST_DISJOINT, F_ST_DISTANCE, F_ST_DISTANCE_GEOS, F_ST_DISTANCE_SPHERE, F_ST_DISTANCE_SPHEROID,
  F_ST_DUMP, F_ST_ENDPOINT, F_ST_ENVELOPE, F_ST_EQUALS, F_ST_EXTENT, F_ST_EXTENT_APPROX, F_ST_EXTERIORRING,
  F_ST_FLIPCOORDINATES, F_ST_FORCE2D, F_ST_FORCE3DM, F_ST_FORCE3DZ, F_ST_FORCE4D, F_ST_GEOMFROMGEOJSON,
  F_ST_GEOMFROMHEXEWKB, F_ST_GEOMFROMHEXWKB, F_ST_GEOMFROMTEXT, F_ST_GEOMFROMWKB, F_ST_GEOMETRYTYPE,
  F_ST_HASM, F_ST_HASZ, F_ST_HILBERT, F_ST_INTERSECTION, F_ST_INTERSECTS, F_ST_INTERSECTS_EXTENT, F_ST_ISCLOSED,
  F_ST_ISEMPTY, F_ST_ISRING, F_ST_ISSIMPLE, F_ST_ISVALID, F_ST_LENGTH, F_ST_LENGTH_SPHEROID,
  F_ST_LINEINTERPOLATEPOINT, F_ST_LINEINTERPOLATEPOINTS, F_ST_LINEMERGE, F_ST_LINESTRING2DFROMWKB,
  F_ST_LINESUBSTRING, F_ST_M, F_ST_MMAX, F_ST_MMIN, F_ST_MAKEENVELOPE, F_ST_MAKELINE, F_ST_MAKEPOLYGON,
  F_ST_MAKEVALID, F_ST_MAXIMUMINSCRIBEDCIRCLE, F_ST_MINIMUMROTATEDRECTANGLE, F_ST_MULTI, F_ST_NGEOMETRIES,
  F_ST_NINTERIORRINGS, F_ST_NPOINTS, F_ST_NODE, F_ST_NORMALIZE, F_ST_NUMGEOMETRIES, F_ST_NUMINTERIORRINGS,
  F_ST_NUMPOINTS, F_ST_OVERLAPS, F_ST_PERIMETER, F_ST_PERIMETER_SPHEROID, F_ST_POINT, F_ST_POINT2D,
  F_ST_POINT2DFROMWKB, F_ST_POINT3D, F_ST_POINT4D, F_ST_POINTN, F_ST_POINTONSURFACE, F_ST_POINTS,
  F_ST_POLYGON2DFROMWKB, F_ST_POLYGONIZE, F_ST_QUADKEY, F_ST_REDUCEPRECISION, F_ST_REMOVEREPEATEDPOINTS,
  F_ST_REVERSE, F_ST_SETSRID, F_ST_SHORTESTLINE, F_ST_SIMPLIFY, F_ST_SIMPLIFYPRESERVETOPOLOGY, F_ST_SRID,
  F_ST_STARTPOINT, F_ST_TILEENVELOPE, F_ST_TOUCHES, F_ST_TRANSFORM, F_ST_UNION, F_ST_VORONOIDIAGRAM,
  F_ST_WITHIN, F_ST_WITHINPROPERLY, F_ST_X, F_ST_XMAX, F_ST_XMIN, F_ST_Y, F_ST_YMAX, F_ST_YMIN,
  F_ST_Z, F_ST_ZMFLAG, F_ST_ZMAX, F_ST_ZMIN,

  F_BENCHMARK,

  /* only for FIRST_VALUE. LAST_VALUE, NTH_VALUE analytic functions */
  PT_FIRST_VALUE, PT_LAST_VALUE, PT_NTH_VALUE,
  /* aggregate and analytic functions */
  PT_MEDIAN,
  PT_CUME_DIST,
  PT_PERCENT_RANK,
  PT_PERCENTILE_CONT,
  PT_PERCENTILE_DISC
} FUNC_CODE;

# ifdef  __cplusplus
extern "C" {
# endif

const char *fcode_get_lowercase_name (FUNC_CODE ftype);
const char *fcode_get_uppercase_name (FUNC_CODE ftype);

# ifdef  __cplusplus
}
# endif

#endif // _DB_FUNCTION_HPP_
