#!/usr/bin/env python3
"""tsan_triage.py - turn a ThreadSanitizer log into a table.

A Tier 1 run produces a few hundred reports, and most of them are the same
finding seen from different threads.  Raw, that is not an oracle: nobody reads
14,000 lines per run to notice the one report that is new.  This groups reports
by (kind, top engine frame) so a run produces a dozen rows, and can emit a
suppression file so the next run shows only what those rows do not cover.

  ./tsan_triage.py run.log                  # the table
  ./tsan_triage.py run.log --suppress > tsan.supp
  TSAN_OPTIONS="suppressions=$PWD/tsan.supp" ./concurrency_spike ...

  ./tsan_triage.py run.log --show file_manager.c   # full reports for one row
"""
import argparse
import collections
import re
import sys

# Frames that are never the answer: the sanitizer itself, and the std::thread
# and std::invoke scaffolding every daemon stack goes through.
NOISE = re.compile(
    r"(include/c\+\+/|libstdc\+\+\.so|__tsan|__sanitizer|<null> <null>|"
    r"\bstd::|/usr/lib/llvm)")
FRAME = re.compile(r"^\s+#(\d+) (.+?) (\S+?):(\d+)(?::\d+)? \(")
SUMMARY = re.compile(r"^SUMMARY: ThreadSanitizer: (.+?) (?:\(|/)")
WARNING = re.compile(r"^WARNING: ThreadSanitizer: (.+?) \(pid=")


def split_reports (lines):
  """Reports are fenced by ================== lines; anything outside is the
  program's own stdout, which interleaves freely and is dropped here."""
  cur, out = None, []
  for ln in lines:
    if ln.startswith ("=================="):
      if cur is not None:
        out.append (cur)
        cur = None
      else:
        cur = []
    elif cur is not None:
      cur.append (ln)
  return out


def classify (report):
  kind = "unknown"
  for ln in report:
    m = WARNING.match (ln)
    if m:
      kind = m.group (1)
      break
  else:
    for ln in report:
      m = SUMMARY.match (ln)
      if m:
        kind = m.group (1)
        break

  # The top frame that is engine code.  Everything above it is scaffolding, and
  # everything below it is context.
  for ln in report:
    m = FRAME.match (ln)
    if not m or NOISE.search (ln):
      continue
    func, path, line = m.group (2), m.group (3), m.group (4)
    func = func.split ("(")[0].strip ()
    return kind, f"{path.rsplit('/', 1)[-1]}:{line}", func
  return kind, "?", "?"


def main ():
  ap = argparse.ArgumentParser ()
  ap.add_argument ("log")
  ap.add_argument ("--suppress", action = "store_true",
                   help = "emit a TSan suppression file for every row")
  ap.add_argument ("--show", metavar = "SUBSTR",
                   help = "print the full text of reports whose row matches")
  args = ap.parse_args ()

  with open (args.log, errors = "replace") as f:
    reports = split_reports (f.read ().splitlines ())

  groups = collections.Counter ()
  funcs = {}
  shown = []
  for r in reports:
    kind, where, func = classify (r)
    groups[(kind, where)] += 1
    funcs[(kind, where)] = func
    if args.show and (args.show in where or args.show in func or args.show in kind):
      shown.append (r)

  if args.show:
    for r in shown:
      print ("\n".join (r))
      print ("=" * 60)
    print (f"{len (shown)} of {len (reports)} reports", file = sys.stderr)
    return

  if args.suppress:
    print ("# generated by tsan_triage.py -- a baseline, not a verdict.")
    print ("# Each rule silences one row of the triage table.  Delete a rule to")
    print ("# make that finding visible again.")
    print ("#")
    print ("# TSan only honours '#' at the start of a line, so each rule's comment")
    print ("# goes above it -- a trailing one would become part of the pattern.")
    seen = set ()
    for (kind, where), n in groups.most_common ():
      func = funcs[(kind, where)]
      if func == "?":
        continue
      # A template instantiation's demangled name carries argument types and
      # does not match reliably; suppress by file for those.  TSan matches the
      # pattern against the function name and the file name both.
      pat = where.split (":")[0] if "<" in func else func
      rule = "race" if "race" in kind else "mutex"
      if (rule, pat) in seen:
        continue
      seen.add ((rule, pat))
      print (f"\n# {n}x  {kind}  at {where}  ({func})")
      print (f"{rule}:{pat}")
    return

  print (f"{len (reports)} reports, {len (groups)} distinct\n")
  print (f"{'n':>5}  {'kind':<44}  {'site':<28}  function")
  print ("-" * 110)
  for (kind, where), n in groups.most_common ():
    print (f"{n:>5}  {kind[:44]:<44}  {where[:28]:<28}  {funcs[(kind, where)]}")


if __name__ == "__main__":
  main ()
